### ISSUE TITLE
Update trellis-processing jar

### ISSUE THREAD

**Issue by acoburn** [pan-dora/trellis#2]
The `trellis-compose/trellis-processing/trellis-processing.jar` refers to an older jar file. While (in principle) that jar file will work with the 0.3 release of Trellis-rosid-app, it would make sense to update that to the version available here: https://github.com/trellis-ldp/trellis-rosid/releases/tag/trellis-rosid-0.3.0

BTW, thanks for keeping this project up-to-date with the edge of development (things should be much more settled from here on).

**Comment by christopher-johnson** [comment]
Closed #2 via https://github.com/trellis-ldp/trellis-deployment/commit/fa90090485deb17ac3605c2bbd87646e733f5456

Note: I have encountered an issue with using only a single Kafka broker with the default replication factor (>1) when trellis-processing initializes and gets topic metadata.  The new docker-compose configuration allows a user to add brokers to avoid this.   Kafka ports will not be exposed on the docker host, however, which should not be an issue, unless someone is running a non-containerized integration.

Thanks for all of your continuing work!

**Comment by acoburn** [comment]
@christopher-johnson++
